[discord]
token = ""
logsChannel = "661635113259368468"
tweetChannel = "661741389276643346"
presentationChannel = "661635075082944525"

[twitter]
consumerKey = ""
secretKey = ""
accessToken = ""
secretToken = ""
users = [
  "jasnell",
  "mikeal",
  "mraleph",
  "mathias",
  "JoeDoyle23",
  "NodeJS_Daily",
  "v8js",
  "trott",
  "rauschma",
  "AdamRackis",
  "yosuke_furuwaka",
  "code",
  "ChakraCore",
  "nodejs",
  "rauchg",
  "cjihrig",
  "bmeurer",
  "bitandbang",
  "NodeSource",
  "schuay",
  "addaleax",
  "mikealbrevik",
  "KuXMLP",
  "watilde",
  "dshaw",
  "MylesBorins",
  "BrendanEich",
  "jfbastien",
  "sindresorhus",
  "seldo",
  "refack",
  "apapirovski",
  "_developit",
  "ljharb",
  "ofrobots",
  "flowtype",
  "yarnpkg",
  "wSokra",
  "AruneshC",
  "bterlson",
  "gauravseth",
  "awbjs",
  "NodejsTaiwan",
  "indutny",
  "porteneuve",
  "linclark",
  "bradleymeck",
  "littledan",
  "jdalton",
  "domenic",
  "tverwaes",
  "silv3rwind",
  "hashseed",
  "mscdexdotexe",
  "Fishrock123",
  "nzgb",
  "_gsathya",
  "sarah_edo",
  "matteocollina",
  "TheLarkInn",
  "fhinkel",
  "trevnorris",
  "HackyGoLucky",
  "typescriptlang",
  "npmjs",
  "tjholowaychuk",
  "ChromiumDev",
  "left_pad",
  "adonisframework",
  "romainlanz",
  "fraxken",
  "Xstoudi",
  "nolanrigo",
  "babeljs",
  "wa7son",
  "feross",
  "thlorenz",
  "GraphQL",
  "reactjs",
  "vuejs",
  "angular",
  "ReBeccaOrg",
  "NodeConfEU",
  "MSEdgeDev",
  "WasmWeekly",
  "svensauleau",
  "hapijs",
  "StrongLoop",
  "JSKongress",
  "erickwendel_",
  "mattbierner",
  "_shu",
  "gesa",
  "heisenbugger",
  "poledesfetes",
  "lukeed05",
  "sebmarkbage",
  "rossmcilroy",
  "ak_239",
  "ulandeg",
  "jsconfeu",
  "bakkoting",
  "sigurdschn",
  "sebmck",
  "simona_cotin",
  "indexconf",
  "devongovett",
  "targos89"
]
feeds = [
  "nodejs",
  "node_js",
  "wasm",
  "webassembly",
  "v8",
  "ecmascript",
  "javascript",
  "npm",
  "webpack",
  "adonis",
  "adonisframework",
  "babel",
  "eslint",
  "typescript",
  "angular",
  "react",
  "reactjs",
  "vue",
  "vuejs",
  "chakracore",
  "graphql",
  "rxjs",
  "libuv",
  "tc39"
]